kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: core
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/slim/repos/balancer-view/data/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: core
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
