kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: core
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: core
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
